### PR TITLE
avoid scandir on each blog articles request

### PR DESCRIPTION
**Pull request by lduboeuf**
Maybe not necessary to scan dir on each request. Use uv.new_fs_event to watch for directory change and reload then with next request.

### CODE REVIEW

**Comment by lduboeuf** [comment]
just figured out that it doesn't work when updates occurred in subdirectories

**Comment by lduboeuf** [comment]
will not work if any events occurred within subdirectories. Maybe not suitable

**Comment by creationix** [comment]
I just wrote a redis driver for luvit.  I'm actually thinking of just doing full-page cache in redis with a short timeout for production use.  (or a long timeout, but allow manually clearing the cache when a deploy happens).

Keep in mind this is fixing a non-issue.  The luvit.io website is super fast with the amount of traffic it gets.

**Comment by lduboeuf** [comment]
i see, i agree it is better to have a cache above. Was just thinking of making dynamic articles posting and avoid scandir on every request ( my code runs 3 times faster ). Sorry about it

**Pull request closed without merging**
